name: Build Windows EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        choco install mingw cmake --yes

    - name: Add MinGW to PATH
      run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

    - name: Download and Build FLTK
      run: |
        curl -L -o fltk.zip https://www.fltk.org/pub/fltk/1.3.8/fltk-1.3.8-source.zip
        powershell Expand-Archive -Path fltk.zip -DestinationPath fltk-1.3.8
        mkdir fltk-1.3.8/build
        cd fltk-1.3.8/build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
      shell: bash


    - name: Configure Your Project
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=../fltk-1.3.8
      shell: bash

    - name: Build with CMake
      run: cmake --build build

    - name: Prepare zip package
      run: |
        mkdir dist
        cp build/nqueen.exe dist/
        cp queen.png dist/
        cd dist
        powershell Compress-Archive -Path * -DestinationPath ../nqueen_bundle.zip

    - name: Upload zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: NQueen-Windows-Bundle
        path: nqueen_bundle.zip
