name: Windows Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install FLTK
      run: choco install fltk --version=1.3.8 -y

    - name: Add MinGW to PATH
      run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

    - name: Configure with CMake
      run: cmake -B build -G "MinGW Makefiles"

    - name: Build with CMake
      run: cmake --build build

    - name: Upload .exe
      uses: actions/upload-artifact@v4
      with:
        name: NQueen-Executable
        path: build/nqueen.exe
